version: '3'

dotenv: [ '.env' ]

vars:
  DB_URL: postgres://{{.DB_USERNAME}}:{{.DB_PASSWORD}}@localhost:5432/{{.DB_NAME}}?sslmode=disable&search_path=public
  MIGRATION_DIR: ./internal/database/migrations

env:
  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: "{{.DB_URL}}"

tasks:
  watch:
    cmds:
      - air

  migration:
    cmds:
      - goose create {{.NAME}} sql -dir {{.MIGRATION_DIR}}

  upgrade:
    cmds:
      - goose up -dir {{.MIGRATION_DIR}}

  downgrade:
    cmds:
      - goose down -dir {{.MIGRATION_DIR}}

  status:
    cmds:
      - goose status -dir {{.MIGRATION_DIR}}

  generate:
    cmds:
      - sqlc generate

  compose:
    cmds:
      - docker compose up --build -d